# Generated by Django 3.1.7 on 2021-05-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default='2000-01-01', verbose_name='생년월일'),
        ),
    ]
