# Generated by Django 3.1.7 on 2021-05-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': '주식',
                'verbose_name_plural': '주식',
                'db_table': 'stock',
            },
        ),
    ]
