# Generated by Django 3.1.7 on 2021-05-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table='Stock',
        ),
    ]
