# Generated by Django 3.1.7 on 2021-06-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='locate',
            field=models.IntegerField(default=0, verbose_name='상단고정'),
        ),
    ]
